name: Auto Assign PR Reviewer

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign PR reviewer
        uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/auto-assign-config.yml
